trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.2.103
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.9.4

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cp /opt/hostedtoolcache/NuGet/4.9.4/x64/nuget.exe ./tools/'

- script: |
    npm install --prefix ./src/Ocelot.ConfigEditor
  displayName: 'npm install'

- pwsh: |
    ./build.ps1
  failOnStderr: true
  displayName: 'run cake build'

